name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v5
      - name: Install packages
        run: make install-packages
      - name: Run install script
        run: ./install.sh
      - name: Verify chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: Test bash syntax
        run: bash -n "$HOME/.shellrc"
      - name: Test zsh syntax
        run: zsh -n "$HOME/.shellrc"
      - name: Test gitconfig syntax
        run: git config -f "$HOME/.gitconfig_personal" --list
      - name: Test vimrc syntax
        run: vim -e -c 'source ~/.vimrc' -c 'qa!'
      - name: Test tmux.conf syntax
        run: tmux -f ~/.tmux.conf start-server \; kill-server

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
      - name: Install shellcheck
        run: sudo apt-get update -qq && sudo apt-get install -y shellcheck
      - name: Lint
        run: make lint
