name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  clone-and-install:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: ubuntu-latest
            container: mcr.microsoft.com/devcontainers/base:ubuntu
            codespaces: true
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}
    env:
      CODESPACES: ${{ matrix.codespaces && 'true' || '' }}
    steps:
      - uses: actions/checkout@v5
      - name: Run install script
        run: ./install.sh
      - name: Verify chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
      - name: Install deps
        run: ./lib/install-deps.sh
      - name: Test bash syntax
        run: bash -n "$HOME/.shellrc"
      - name: Test zsh syntax
        run: zsh -n "$HOME/.shellrc"
      - name: Test gitconfig syntax
        run: git config -f "$HOME/.gitconfig_personal" --list
      - name: Test vimrc syntax
        run: vim -e -c 'source ~/.vimrc' -c 'qa!'
      - name: Test tmux.conf syntax
        run: tmux -f ~/.tmux.conf start-server \; kill-server

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install deps
        run: ./lib/install-deps.sh
      - name: Lint
        run: make lint
